package org.matsim.contrib.sarp.enums;

public enum VehicleStatus {
	STOP_WORK,
	NOT_WORK,
	TRAVEL_WITHOUT_LOAD,
	REST_AT_PARKING,
	GOING_TO_PICKUP_PEOPLE,
	GOING_TO_DELIVERY_PEOPEL,
	GOING_TO_PICKUP_PARCEL,
	GOING_TO_DELIVERY_PARCEL,
	DELIVERY_PEOPLE,
	PICKUP_PEOPLE,
	PICKUP_PARCEL,
	DELIVERY_PARCEL,
	FINISHED_PICKUP_PEOPLE,
	FINISHED_DELIVERY_PEOPLE,
	FINISHED_PICKUP_PARCEL,
	FINISHED_DELIVERY_PARCEL,
	PREPARE_NEW_ITINERARY,
	GO_BACK_DEPOT_FINISH_WORK

}
